   stages:
     - lint
     - test

   lint:
     stage: lint
     image: python:3.9
     script:
       - pip install flake8 black isort mypy
       - flake8 your_project_directory/
       - black --check your_project_directory/
       - isort --check-only your_project_directory/
       - mypy your_project_directory/
     only:
       - merge_requests
       - branches

   test:
     stage: test
     image: python:3.9
     script:
       - pip install -r requirements.txt
       - pytest
     only:
       - merge_requests
       - branches