version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  flask_app:
    build: .
    ports:
      - 5000:5000