version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: skillbox_db
      PG_LOG_DESTINATION: stderr
      PG_LOGGING_COLLECTOR: on
      PG_LOG_DIRECTORY: /var/log/postgresql
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_log:/var/log/postgresql
    networks:
      - app-network

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/skillbox_db
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
  pg_log: