version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    command:
      -c log_destination=stderr
      -c logging_collector=on
      -c log_directory=/var/log/postgresql

volumes:
  db_data:

networks:
  app-network:
    driver: bridge