version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://<username>:<password>@db:5432/skillbox_db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: <username>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: skillbox_db
      POSTGRES_LOG_DESTINATION: stderr
      POSTGRES_LOGGING_COLLECTOR: on
      POSTGRES_LOG_DIRECTORY: /var/log/postgresql
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata: